# Generated by Django 2.2.3 on 2019-08-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short', models.CharField(max_length=5)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short', models.CharField(max_length=5)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('short', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('entireclass', models.CharField(max_length=10)),
                ('divisiontag', models.CharField(max_length=10)),
                ('studentcount', models.CharField(max_length=10)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodspercard', models.CharField(max_length=10)),
                ('periodsperweek', models.CharField(max_length=10)),
                ('weeks', models.CharField(max_length=10)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
                ('studentids', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=10)),
                ('endtime', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Resp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Результат розрахунку')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('sort', models.FloatField(blank=True, default=0, null=True, verbose_name='Порядок сортування')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(default='', max_length=150, unique=True, verbose_name='Slug')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
