# Generated by Django 2.2.3 on 2019-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worktime', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='acyear_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='cards', to='timetable.Card'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='subject',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='resp',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='period',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='classes',
            field=models.ManyToManyField(to='timetable.Class'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='classrooms',
            field=models.ManyToManyField(to='timetable.Classroom'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(to='timetable.Group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subjects',
            field=models.ManyToManyField(to='timetable.Subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(to='timetable.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(to='timetable.Class'),
        ),
        migrations.AddField(
            model_name='group',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='day',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='class',
            name='classrooms',
            field=models.ManyToManyField(to='timetable.Classroom'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='timetable.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
        migrations.AddField(
            model_name='card',
            name='classrooms',
            field=models.ManyToManyField(to='timetable.Classroom'),
        ),
        migrations.AddField(
            model_name='card',
            name='day_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Day'),
        ),
        migrations.AddField(
            model_name='card',
            name='lesson_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Lesson'),
        ),
        migrations.AddField(
            model_name='card',
            name='period_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Period'),
        ),
        migrations.AddField(
            model_name='card',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
    ]
