# Generated by Django 2.2.3 on 2019-08-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190811_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='acyear_id',
        ),
    ]
