# Generated by Django 2.2.3 on 2019-08-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0001_initial'),
        ('timetable', '0003_remove_timetable_acyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='acyear_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear'),
        ),
    ]
