# Generated by Django 2.2.3 on 2019-08-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetable_acyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cards',
            field=models.ManyToManyField(to='timetable.Card'),
        ),
    ]
