# Generated by Django 2.2.3 on 2019-07-12 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(default='', max_length=150, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('images', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('bb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Bb')),
            ],
            options={
                'verbose_name': 'Малюнки',
                'verbose_name_plural': 'Малюнок',
                'ordering': ['content'],
            },
        ),
    ]
