# Generated by Django 2.2.3 on 2019-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='photo_prev',
            field=models.ImageField(blank=True, null=True, upload_to='prev_user_images'),
        ),
    ]
