# Generated by Django 2.2.3 on 2019-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20190712_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='photo_ori',
            field=models.ImageField(blank=True, null=True, upload_to='prev_user_images'),
        ),
    ]
