# Generated by Django 2.2.3 on 2019-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_photo_ori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='photo_ori',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='photo_prev',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
