# Generated by Django 2.2.3 on 2019-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Напрямок')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('termin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Строки виконання')),
                ('generalization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма узагальнення')),
                ('responsible', models.CharField(blank=True, max_length=150, null=True, verbose_name='Відповідальний')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Примітка')),
                ('sort', models.FloatField(blank=True, null=True, verbose_name='Порядок сортування')),
                ('show', models.BooleanField(blank=True, default=True, verbose_name='Відображати у звіті')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='Відмітка про виконання')),
            ],
            options={
                'ordering': ['direction_id', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='Plantable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва події')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Початок події')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Кінець події')),
                ('tmp', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Plan', verbose_name='')),
                ('plantable_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Розділ')),
                ('n_r', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('riven', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Rubric', verbose_name='')),
                ('plantable_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable')),
            ],
            options={
                'ordering': ['n_r'],
            },
        ),
        migrations.CreateModel(
            name='Responsibl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Plan', verbose_name='')),
                ('plantable_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Мета')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('plantable_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable')),
            ],
        ),
    ]
