# Generated by Django 2.2.3 on 2019-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worktime', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantable',
            name='acyear_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear'),
        ),
        migrations.AddField(
            model_name='plan',
            name='direction_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Direction', verbose_name='Напрямок'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plantable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable'),
        ),
        migrations.AddField(
            model_name='plan',
            name='purpose_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Purpose', verbose_name='Мета'),
        ),
        migrations.AddField(
            model_name='plan',
            name='r_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Rubric', verbose_name='Розділ'),
        ),
        migrations.AddField(
            model_name='direction',
            name='plantable_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='plan.Plantable'),
        ),
    ]
