# Generated by Django 2.2.3 on 2019-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=15)),
                ('verbose', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('value', models.CharField(max_length=250)),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('sort', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['sort', 'published'],
            },
        ),
        migrations.CreateModel(
            name='Worktimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('acyear_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear')),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('wday', models.DateField(verbose_name='Дата')),
                ('numworkweek', models.IntegerField()),
                ('dayweek', models.IntegerField()),
                ('weekchzn', models.IntegerField(verbose_name='1-чис., 2-зн., 0-вихідний')),
                ('acyear_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear')),
                ('worktimetable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Worktimetable')),
            ],
        ),
        migrations.CreateModel(
            name='Vacat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of vacation')),
                ('name', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now=True, db_index=True)),
                ('acyear_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='worktime.Academyear')),
                ('worktimetable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Worktimetable')),
            ],
            options={
                'ordering': ['date', 'published'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата пропуску')),
                ('reason', models.CharField(blank=True, max_length=15, null=True)),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('clas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='timetable.Class')),
                ('misssubj', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='miss_subj', to='timetable.Subject')),
                ('missteach', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='miss_teacher', to='timetable.Teacher')),
                ('replsubj', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repl_subj', to='timetable.Subject')),
                ('replteach', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repl_teacher', to='timetable.Teacher')),
                ('worktimeable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Worktimetable')),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_st', models.DateTimeField(db_index=True, verbose_name='Відсутній з')),
                ('date_fin', models.DateTimeField(db_index=True, verbose_name='Відсутній по')),
                ('reason', models.CharField(blank=True, max_length=15, null=True, verbose_name='Причина відсутності')),
                ('kl_ker', models.BooleanField(blank=True, default=True, verbose_name='Класний керівник')),
                ('poch_kl', models.BooleanField(blank=True, default=False, verbose_name='Викладає в початкових класах')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('teach', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='timetable.Teacher', verbose_name='Відсутній вчитель')),
                ('worktimeable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='worktime.Worktimetable')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Hourlyworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typehw', models.IntegerField(default=0, verbose_name='0 - погодинник, 1-10 кількість годин на день')),
                ('description', models.CharField(blank=True, max_length=15, null=True, verbose_name='Опис для виводу в записку')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('teacher_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Teacher', verbose_name='Вчитель')),
                ('timetable_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable')),
            ],
        ),
    ]
