# Generated by Django 2.2.3 on 2019-08-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacat',
            old_name='worktimetable',
            new_name='worktimetable_id',
        ),
        migrations.RemoveField(
            model_name='vacat',
            name='acyear_id',
        ),
    ]
