# Generated by Django 2.2.3 on 2019-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0002_auto_20190811_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='acyear_id',
        ),
    ]
