# Generated by Django 2.2.3 on 2019-08-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0003_remove_workday_acyear_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='worktimetable',
            new_name='worktimetable_id',
        ),
    ]
