# Generated by Django 2.2.3 on 2019-08-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0004_auto_20190811_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missing',
            old_name='worktimeable',
            new_name='worktimetable_id',
        ),
        migrations.RenameField(
            model_name='replacement',
            old_name='worktimeable',
            new_name='worktimetable_id',
        ),
    ]
