# Generated by Django 2.2.3 on 2019-08-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190811_1036'),
        ('worktime', '0005_auto_20190811_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missing',
            name='worktimetable_id',
        ),
        migrations.AddField(
            model_name='missing',
            name='timetable_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Timetable'),
        ),
    ]
