# Generated by Django 2.2.3 on 2019-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAddFlower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('care', models.TextField()),
                ('photo', models.ImageField(upload_to='user_flowers')),
            ],
        ),
    ]
