# Generated by Django 2.2.3 on 2019-07-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_auto_20190708_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleaddflower',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='q1'),
        ),
    ]
