# Generated by Django 2.2.3 on 2019-07-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Напрямок')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Мета')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Розділ')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('start', models.DateField(verbose_name='Початок події')),
                ('finish', models.DateField(verbose_name='Кінець події')),
                ('generalization', models.CharField(max_length=50, verbose_name='Форма узагальнення')),
                ('responsible', models.CharField(max_length=150, verbose_name='Відповідальний')),
                ('note', models.CharField(max_length=50, verbose_name='Примітка')),
                ('sort', models.FloatField(verbose_name='Порядок сортування')),
                ('show', models.BooleanField(default=True, verbose_name='Відображати у звіті')),
                ('published', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубліковано')),
                ('done', models.BooleanField(default=False, verbose_name='Відмітка про виконання')),
                ('direction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Direction', verbose_name='Напрямок')),
                ('purpose_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Purpose', verbose_name='Напрямок')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.Rubric', verbose_name='Розділ')),
            ],
        ),
    ]
