# Generated by Django 2.2.3 on 2019-07-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start',
        ),
        migrations.AddField(
            model_name='plan',
            name='termins',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Строки виконання'),
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва події')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Початок події')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Кінець події')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Plan', verbose_name='')),
            ],
        ),
    ]
