# Generated by Django 2.2.3 on 2019-07-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20190713_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='termins',
            new_name='termin',
        ),
        migrations.AddField(
            model_name='plan',
            name='tmp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tmp'),
        ),
        migrations.CreateModel(
            name='Responsibl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Напрямок')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.Plan', verbose_name='')),
            ],
        ),
    ]
