# Generated by Django 2.2.3 on 2019-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20190713_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tmp2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tmp'),
        ),
    ]
